# **Load Dataset**

In [1]:
# importing pandas and csv files and getting the row and column numbers
import pandas as pd

train = pd.read_csv("/kaggle/input/rossmann-store-sales/train.csv", dtype={"StateHoliday": "object"})
test = pd.read_csv("/kaggle/input/rossmann-store-sales/test.csv", dtype={"StateHoliday": "object"})
store = pd.read_csv("/kaggle/input/rossmann-store-sales/store.csv")

train.shape, test.shape, store.shape

((1017209, 9), (41088, 8), (1115, 10))

In [2]:
# first five row of the train set
train.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [3]:
# first five row of store set
store.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

# **Merge Train and Store Tables**

In [4]:
#merging the train with the store for getting daily infos and store infos to make train better
df = train.merge(store, on = "Store", how = "left")
df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

# **Convert Date Column to Datetime**

In [5]:
# since computer can not understand the date as humans, turning them to the integers and dividing as year, month day and weekofyear as seperate colums
df["Date"] = pd.to_datetime(df["Date"])
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["WeekOfYear"] = df["Date"].dt.isocalendar().week.astype(int)
df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,...,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval,Year,Month,Day,WeekOfYear
0,1,5,2015-07-31,5263,555,1,1,0,1,c,...,9.0,2008.0,0,NaN,NaN,NaN,2015,7,31,31
1,2,5,2015-07-31,6064,625,1,1,0,1,a,...,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct",2015,7,31,31
2,3,5,2015-07-31,8314,821,1,1,0,1,a,...,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct",2015,7,31,31
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,...,9.0,2009.0,0,NaN,NaN,NaN,2015,7,31,31
4,5,5,2015-07-31,4822,559,1,1,0,1,a,...,4.0,2015.0,0,NaN,NaN,NaN,2015,7,31,31

# **Drop Unnecessary Columns**

In [6]:
# deleting customers since it is not in the test set
# deleting date since we have other columns

df = df.drop(["Customers", "Date"], axis=1)

In [7]:
df.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Store,DayOfWeek,Sales,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval,Year,Month,Day,WeekOfYear
0,1,5,5263,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN,2015,7,31,31
1,2,5,6064,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct",2015,7,31,31
2,3,5,8314,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct",2015,7,31,31
3,4,5,13995,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN,2015,7,31,31
4,5,5,4822,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN,2015,7,31,31

# **Label Encoding for Categorical Features**

In [8]:
cat_cols = ["Store", "StoreType", "Assortment", "StateHoliday", "PromoInterval"]  # non-numeric, categorical columns

In [9]:
from sklearn.preprocessing import LabelEncoder

encoders = {}  # saving all label encoders here for later use (test set)

for col in cat_cols:
    df[col] = df[col].astype(str)   # changing column to string
    le = LabelEncoder()             # creating a LabelEncoder object
    df[col] = le.fit_transform(df[col])  # fitting on train data and converting to integers
    encoders[col] = le              # saving this encoder for the test set

In [10]:
df[cat_cols].head()   # they will be in the embedding layer

   Store  StoreType  Assortment  StateHoliday  PromoInterval
0      0          2           0             0              3
1    227          0           0             0              1
2    338          0           0             0              1
3    449          2           2             0              3
4    560          0           0             0              3

# **Define Target vs Features, Separate Numeric and Categorical Features**

In [11]:
target_col = "Sales"   # setting the target as Sales column

feature_cols = [c for c in df.columns if c != target_col]  # remove the feature columns, so model does not remember and overfit
num_cols = [c for c in feature_cols if c not in cat_cols]  # numeric columns

print("Categorical Columns:", cat_cols)
print("Numeric Columns:", num_cols)

Categorical Columns: ['Store', 'StoreType', 'Assortment', 'StateHoliday', 'PromoInterval']
Numeric Columns: ['DayOfWeek', 'Open', 'Promo', 'SchoolHoliday', 'CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek', 'Promo2SinceYear', 'Year', 'Month', 'Day', 'WeekOfYear']

# **Train and Validation Split**

In [12]:
from sklearn.model_selection import train_test_split

# X = features, y = target
X = df[feature_cols]
y = df[target_col]

X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size = 0.2,
    random_state = 42,
    shuffle = True
)

print("Train shape:", X_train.shape, y_train.shape)
print("Val shape:",   X_val.shape,   y_val.shape)

Train shape: (813767, 19) (813767,)
Val shape: (203442, 19) (203442,)

In [13]:
# fill missing values in numeric columns with -1, since it does not occur in dataset, model can learn -1 as missing info
X_train[num_cols] = X_train[num_cols].fillna(-1)
X_val[num_cols]   = X_val[num_cols].fillna(-1)

# **Scale Numeric Features (StandardScaler)**

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# make a copy of the original X_train, might be useful in the future
X_train_scaled = X_train.copy()
X_val_scaled   = X_val.copy()

# scale only numeric columns
X_train_scaled[num_cols] = scaler.fit_transform(X_train[num_cols])
X_val_scaled[num_cols]   = scaler.transform(X_val[num_cols])

In [15]:
X_train_scaled[num_cols].head()

,DayOfWeek,Open,Promo,SchoolHoliday,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,Year,Month,Day,WeekOfYear
417683,1.503363,-2.211217,-0.785312,-0.466902,-0.662878,-0.131286,0.684984,0.998383,0.180741,0.997635,0.216008,0.045991,0.716679,0.095847
659402,1.503363,-2.211217,-0.785312,-0.466902,-0.417752,0.942004,0.676435,-1.001620,-0.773892,-1.001619,-1.070485,1.549818,0.147712,1.551314
739873,0.501981,0.452240,-0.785312,-0.466902,4.308378,0.942004,0.686053,-1.001620,-0.773892,-1.001619,-1.070485,0.948288,-1.104015,0.858235
109671,0.501981,0.452240,-0.785312,-0.466902,0.054342,0.942004,0.684984,0.998383,0.117099,0.996641,1.502500,-0.555539,0.944266,-0.458617
422541,-0.499401,0.452240,1.273379,-0.466902,-0.133717,-1.204577,-1.465144,-1.001620,-0.773892,-1.001619,0.216008,0.045991,0.261506,0.095847

In [16]:
import torch
import torch.nn as nn

class RossmannNet(nn.Module):
    def __init__(self, emb_info, num_numeric_features):
        super().__init__()
        
        # creating embedding layers for each categorical feature
        self.emb_layers = nn.ModuleList([
            nn.Embedding(num_categories, emb_dim) 
            for num_categories, emb_dim in emb_info
        ])

        # larger dense block for numeric features
        self.numeric_block = nn.Sequential(
            nn.Linear(num_numeric_features, 64),
            nn.ReLU()
        )

        # deeper fully connected layers: (total_emb + 64) -> 128 -> 64 -> 1
        total_emb_dim = self.total_emb_dim(emb_info)
        self.fc = nn.Sequential(
            nn.Linear(total_emb_dim + 64, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 1)  # output = log(1 + Sales)
        )

    def total_emb_dim(self, emb_info):
        # summing all embedding dimensions to know final vector size
        return sum([emb_dim for _, emb_dim in emb_info])

    def forward(self, x_num, x_cat):
        # processing categorical inputs through embedding layers
        embs = [emb_layer(x_cat[:, i]) for i, emb_layer in enumerate(self.emb_layers)]
        x_cat_emb = torch.cat(embs, dim=1)

        # processing numeric features
        x_num_out = self.numeric_block(x_num)

        # combining embeddings and numeric output
        x = torch.cat([x_cat_emb, x_num_out], dim=1)

        # applying fully connected layers to get the final prediction (log space)
        out = self.fc(x)
        return out

# **Model Preparation (PyTorch)**

emb_dim = min(50, (n_categories / 2) + 1)

In [17]:
emb_info = []

for col in cat_cols:
    num_categories = df[col].nunique()
    emb_dim = min(50, (num_categories // 2) + 1)
    emb_info.append((num_categories, emb_dim))

emb_info

[(1115, 50), (4, 3), (3, 2), (4, 3), (4, 3)]

In [18]:
num_numeric_features = len(num_cols)  # getting the number of numeric features
num_numeric_features

14

In [ ]:
import numpy as np
import torch

# categorical tensor
x_cat_train = torch.tensor(X_train_scaled[cat_cols].values, dtype=torch.long)

# numeric tensor
x_num_train = torch.tensor(X_train_scaled[num_cols].values, dtype=torch.float32)

# LOG TRANSFORM on target
# y_train to log(1 + y_train)
y_train_log = np.log1p(y_train.values)
y_val_log   = np.log1p(y_val.values)

# target tensor (log space)
y_train_t = torch.tensor(y_train_log, dtype=torch.float32).view(-1, 1)
y_val_t   = torch.tensor(y_val_log,   dtype=torch.float32).view(-1, 1)

# same for validation inputs
x_cat_val = torch.tensor(X_val_scaled[cat_cols].values, dtype=torch.long)
x_num_val = torch.tensor(X_val_scaled[num_cols].values, dtype=torch.float32)

# **Model, loss, optimizer**

In [ ]:
import torch.optim as optim
from torch.optim.lr_scheduler import StepLR

# creating the model
model = RossmannNet(emb_info, num_numeric_features)

# moving model to GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# loss function (MSE in log space)
criterion = nn.MSELoss()

# optimizer (Adam) with lower learning rate
optimizer = optim.Adam(model.parameters(), lr=0.0007)   #(dont forget to tune it)

# learning rate scheduler: every 3 epochs, lr = lr * 0.5
scheduler = StepLR(optimizer, step_size=3, gamma=0.5)

# **DataLoader**

In [21]:
from torch.utils.data import TensorDataset, DataLoader

# creating TensorDataset objects (using log-transformed targets)
train_dataset = TensorDataset(x_num_train, x_cat_train, y_train_t)
val_dataset   = TensorDataset(x_num_val,   x_cat_val,   y_val_t)

# creating DataLoaders for batch training
batch_size = 2048  # larger batch size for faster and smoother training

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader   = DataLoader(val_dataset,   batch_size=batch_size, shuffle=False)

# **Training Loop**

In [ ]:
num_epochs = 15  # training for more epochs (dont forget to tune it)

for epoch in range(num_epochs):
    model.train()  
    train_loss = 0.0

    for x_num_batch, x_cat_batch, y_batch in train_loader:
        # move to device (GPU or CPU)
        x_num_batch = x_num_batch.to(device)
        x_cat_batch = x_cat_batch.to(device)
        y_batch     = y_batch.to(device)

        # reset gradients
        optimizer.zero_grad()

        # forward pass (model predicts log(1 + sales))
        y_pred = model(x_num_batch, x_cat_batch)

        # loss in log-space
        loss = criterion(y_pred, y_batch)

        # backward pass
        loss.backward()

        # update weights
        optimizer.step()

        train_loss += loss.item() * x_num_batch.size(0)

    # average train loss
    train_loss /= len(train_loader.dataset)

    # validation
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for x_num_batch, x_cat_batch, y_batch in val_loader:
            x_num_batch = x_num_batch.to(device)
            x_cat_batch = x_cat_batch.to(device)
            y_batch     = y_batch.to(device)

            y_pred = model(x_num_batch, x_cat_batch)
            loss = criterion(y_pred, y_batch)
            val_loss += loss.item() * x_num_batch.size(0)

    val_loss /= len(val_loader.dataset)

    # update learning rate
    scheduler.step()
    current_lr = scheduler.get_last_lr()[0]

    print(f"Epoch {epoch+1}/{num_epochs} - Train Loss: {train_loss:.4f} - Val Loss: {val_loss:.4f} - LR: {current_lr:.6f}")

Epoch 1/15 - Train Loss: 5.7134 - Val Loss: 0.1604 - LR: 0.000700
Epoch 2/15 - Train Loss: 0.1033 - Val Loss: 0.0732 - LR: 0.000700
Epoch 3/15 - Train Loss: 0.0572 - Val Loss: 0.0500 - LR: 0.000350
Epoch 4/15 - Train Loss: 0.0451 - Val Loss: 0.0451 - LR: 0.000350
Epoch 5/15 - Train Loss: 0.0413 - Val Loss: 0.0422 - LR: 0.000350
Epoch 6/15 - Train Loss: 0.0387 - Val Loss: 0.0398 - LR: 0.000175
Epoch 7/15 - Train Loss: 0.0368 - Val Loss: 0.0384 - LR: 0.000175
Epoch 8/15 - Train Loss: 0.0358 - Val Loss: 0.0374 - LR: 0.000175
Epoch 9/15 - Train Loss: 0.0348 - Val Loss: 0.0364 - LR: 0.000087
Epoch 10/15 - Train Loss: 0.0338 - Val Loss: 0.0357 - LR: 0.000087
Epoch 11/15 - Train Loss: 0.0333 - Val Loss: 0.0354 - LR: 0.000087
Epoch 12/15 - Train Loss: 0.0328 - Val Loss: 0.0347 - LR: 0.000044
Epoch 13/15 - Train Loss: 0.0323 - Val Loss: 0.0343 - LR: 0.000044
Epoch 14/15 - Train Loss: 0.0320 - Val Loss: 0.0340 - LR: 0.000044
Epoch 15/15 - Train Loss: 0.0317 - Val Loss: 0.0337 - LR: 0.000022

In [23]:
# preparing the test set
import pandas as pd

test = pd.read_csv("/kaggle/input/rossmann-store-sales/test.csv") 
test = test.merge(store, on="Store", how="left")

print(test.shape)
test.head()

(41088, 17)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,1,4,2015-09-17,1.0,1,0,0,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,3,4,2015-09-17,1.0,1,0,0,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
2,3,7,4,2015-09-17,1.0,1,0,0,a,c,24000.0,4.0,2013.0,0,NaN,NaN,NaN
3,4,8,4,2015-09-17,1.0,1,0,0,a,a,7520.0,10.0,2014.0,0,NaN,NaN,NaN
4,5,9,4,2015-09-17,1.0,1,0,0,a,c,2030.0,8.0,2000.0,0,NaN,NaN,NaN

In [24]:
# test set date feature engineering
test["Date"] = pd.to_datetime(test["Date"])
test["Year"] = test["Date"].dt.year
test["Month"] = test["Date"].dt.month
test["Day"] = test["Date"].dt.day
test["WeekOfYear"] = test["Date"].dt.isocalendar().week.astype(int)

test = test.drop(["Date"], axis=1)

In [25]:
# applying categorical encoding to test set

for col in cat_cols:
    test[col] = test[col].astype(str)
    test[col] = encoders[col].transform(test[col])

In [26]:
# same numeric preprocessing as train
test[num_cols] = test[num_cols].fillna(-1)

test_scaled = test.copy()
test_scaled[num_cols] = scaler.transform(test[num_cols])

In [27]:
# creating test tensors
x_cat_test = torch.tensor(test_scaled[cat_cols].values, dtype=torch.long).to(device)
x_num_test = torch.tensor(test_scaled[num_cols].values, dtype=torch.float32).to(device)

In [28]:
import numpy as np

model.eval()
with torch.no_grad():
    # model predicts log(1 + Sales)
    preds_log = model(x_num_test, x_cat_test).cpu().numpy().flatten()
    
    # converting back to original scale: Sales = expm1(log(1 + Sales))
    preds = np.expm1(preds_log)

In [29]:
# creating submission file
submission = pd.DataFrame({
    "Id": test_scaled["Id"],
    "Sales": preds
})

submission.to_csv("submission.csv", index=False)
submission.head()

   Id         Sales
0   1   4117.919434
1   2   7914.519531
2   3  10058.035156
3   4   5298.869629
4   5   6555.372559